vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
        
    mappings:
       team_images:
           uri_prefix: /images/team
           upload_destination: '%kernel.project_dir%/public/images/team'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
   